url: http://yenbekbay.github.io
baseurl: /webster

# Site settings
title: Webster
email: ayan.yenb@gmail.com
description: "#todo."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3B4FCD
  secondary: 374AC0
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Name 1
  pic: photo
  position: iOS Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Name 2
  pic: photo
  position: Android Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Name 3
  pic: photo
  position: Project Manager
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: facebook
    url:
  - title: stack-overflow
    url:
  - title: bitbucket
    url:
  - title: github
    url:

# Address
address:
  - line: Address Line
  - line: Almaty, Kazakhstan

# Build settings
markdown: kramdown
permalink: pretty
