# Site settings
title: Webster
email: contact@hiwebster.kz
url: https://hiwebster.kz
description: "Студия по разработке красивых и функциональных мобильных приложений."

sass:
  style: compressed

# Footer settings
footer:
  copyright: Webster

# Build settings
markdown: kramdown
permalink: pretty
